// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class AdditionalInfo
{
    public string ReferenceId { get; set; }

    public string InfoAsJsonString { get; set; }

    public string DriverAdditionalInfo { get; set; }

    public virtual CheckoutDetails Reference { get; set; }
}