// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class AspNetUsers
{
    public string Id { get; set; }

    public Guid RoleId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public DateTime LastLoginDate { get; set; }

    public string DeviceToken { get; set; }

    public Guid LanguageId { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public DateTime? LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public int PromotionCodeCount { get; set; }

    public int PoliciesCount { get; set; }

    public string Channel { get; set; }

    public bool? IsAutoLeasing { get; set; }

    public int? AutoLeasingBankId { get; set; }

    public string AutoLeasingAdminId { get; set; }

    public bool? IsAutoLeasingSuperAdmin { get; set; }

    public bool? IsFirstLogin { get; set; }

    public bool? IsCorporateUser { get; set; }

    public string LockedBy { get; set; }

    public string LockedReason { get; set; }

    public bool? IsPhoneVerifiedByYakeen { get; set; }

    public string NationalId { get; set; }

    public bool? IsYakeenNationalIdVerified { get; set; }

    public int? Otp { get; set; }

    public DateTime? OtpexpirationDate { get; set; }

    public string ConcurrencyStamp { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public string NormalizedUserName { get; set; }

    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; } = new List<AspNetUserClaims>();

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; } = new List<AspNetUserLogins>();

    public virtual ICollection<AspNetUserRoles> AspNetUserRoles { get; set; } = new List<AspNetUserRoles>();

    public virtual ICollection<CheckoutDetails> CheckoutDetails { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<Invoice> Invoice { get; set; } = new List<Invoice>();

    public virtual Language Language { get; set; }

    public virtual ICollection<PromotionProgramCode> PromotionProgramCodeCreator { get; set; } = new List<PromotionProgramCode>();

    public virtual ICollection<PromotionProgramCode> PromotionProgramCodeModifier { get; set; } = new List<PromotionProgramCode>();

    public virtual ICollection<PromotionProgram> PromotionProgramCreatedByNavigation { get; set; } = new List<PromotionProgram>();

    public virtual ICollection<PromotionProgramDomain> PromotionProgramDomainCreatedByNavigation { get; set; } = new List<PromotionProgramDomain>();

    public virtual ICollection<PromotionProgramDomain> PromotionProgramDomainModifiedByNavigation { get; set; } = new List<PromotionProgramDomain>();

    public virtual ICollection<PromotionProgram> PromotionProgramModifiedByNavigation { get; set; } = new List<PromotionProgram>();

    public virtual ICollection<PromotionProgramUser> PromotionProgramUserCreatedByNavigation { get; set; } = new List<PromotionProgramUser>();

    public virtual ICollection<PromotionProgramUser> PromotionProgramUserModifiedByNavigation { get; set; } = new List<PromotionProgramUser>();

    public virtual ICollection<PromotionProgramUser> PromotionProgramUserUser { get; set; } = new List<PromotionProgramUser>();

    public virtual ICollection<QuotationRequest> QuotationRequest { get; set; } = new List<QuotationRequest>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UserPurchasedPromotionPrograms> UserPurchasedPromotionPrograms { get; set; } = new List<UserPurchasedPromotionPrograms>();
}