// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Attachment
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public byte[] AttachmentFile { get; set; }

    public string AttachmentType { get; set; }

    public string AttachmentName { get; set; }

    public virtual ICollection<PolicyUpdateRequestAttachment> PolicyUpdateRequestAttachment { get; set; } = new List<PolicyUpdateRequestAttachment>();
}