// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class AutoLeasingBulkAutoRenewalResult
    {
        public string ReferenceId { get; set; }
        public int Id { get; set; }
        public string PolicyNo { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public DateTime? PolicyExpireDate { get; set; }
        public int PriorityId { get; set; }
        public int ProcessingTries { get; set; }
        public string DriverNin { get; set; }
        public Guid VehicleId { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool? IsCancelled { get; set; }
        public bool? IsLocked { get; set; }
        public int? BanKId { get; set; }
        public int InsuredId { get; set; }
        public Guid DriverId { get; set; }
        public string SequenceNumber { get; set; }
        public Guid? AddtionalDriverOneId { get; set; }
        public Guid? AddtionalDriverTwoId { get; set; }
        public string ExternalId { get; set; }
        public int? DeductableValue { get; set; }
        public int? ContractDuration { get; set; }
        public decimal? VehicleValue { get; set; }
        public string MobileNumber { get; set; }
        public int? ErrorDescription { get; set; }
        public int? Chanel { get; set; }
        public int? ProcessedOn { get; set; }
        public int? CreatedOn { get; set; }
        public int? DontProcessBeforeDate { get; set; }
        public int? ServerIP { get; set; }
        public int? ModifiedDate { get; set; }
        public int? UserId { get; set; }
        public int? RenewedExternalId { get; set; }
        public int? RenewedReferenceId { get; set; }
        public int? ErrorCode { get; set; }
        public int? DaysBeforeRenew { get; set; }
    }
}
