// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class AutoleasingNajmResponseTimeResult
    {
        public string CompanyName { get; set; }
        public string PolicyNo { get; set; }
        public double? ResponseTime { get; set; }
        public string ReferenceId { get; set; }
        public string NajmStatus { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public string NIN { get; set; }
        public string NationalId { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string VehicleId { get; set; }
    }
}
