//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//using Microsoft.EntityFrameworkCore;
//using System;
//using System.Data;
//using System.Linq;
//using Common.Domain.DomainEntities.Entities.DomainEntities;

//namespace Common.Domain.DomainEntities.Entities.DomainEntities
//{
//    public partial class AutoLeasingServiceContext
//    {

//        [DbFunction("ConvertCarPlateTextToEn", "dbo")]
//        public static string ConvertCarPlateTextToEn(string arabicChar)
//        {
//            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
//        }

//        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
//        {
//        }
//    }
//}
