// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CancellationRequest
{
    public int Id { get; set; }

    public string ReferenceId { get; set; }

    public string PolicyNo { get; set; }

    public DateTime? CancelDate { get; set; }

    public int? CancellationReasonCode { get; set; }

    public string CancellationAttachment { get; set; }

    public string UserName { get; set; }

    public bool? IsAutolease { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? ModifiedDate { get; set; }
}