// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutHyperpayPaymentReq
{
    public int HyperpayPaymenRequestId { get; set; }

    public string CheckoutdetailsId { get; set; }
}