// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class CheckIfPhoneAlreadyUsedResult
    {
        public string Email { get; set; }
        public string Phone { get; set; }
        public string IBAN { get; set; }
        public string NIN { get; set; }
    }
}
