// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutCarImages
{
    public int Id { get; set; }

    public byte[] ImageData { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<CheckoutDetails> CheckoutDetailsImageBack { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<CheckoutDetails> CheckoutDetailsImageBody { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<CheckoutDetails> CheckoutDetailsImageFront { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<CheckoutDetails> CheckoutDetailsImageLeft { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<CheckoutDetails> CheckoutDetailsImageRight { get; set; } = new List<CheckoutDetails>();
}