// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutDriverInfo
{
    public int Id { get; set; }

    public string Nin { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Iban { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }
}