// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutAdditionalDrivers
{
    public string CheckoutDetailsId { get; set; }

    public Guid DriverId { get; set; }

    public int Id { get; set; }

    public virtual CheckoutDetails CheckoutDetails { get; set; }

    public virtual Driver Driver { get; set; }
}