// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutUsersTemp
{
    public int Id { get; set; }

    public string ReferenceId { get; set; }

    public Guid? UserId { get; set; }

    public string UserEmail { get; set; }

    public int? VerificationCode { get; set; }

    public bool? IsCodeVerified { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Nin { get; set; }
}