// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class CheckoutDetails
{
    public string ReferenceId { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Iban { get; set; }

    public int? ImageRightId { get; set; }

    public int? ImageLeftId { get; set; }

    public int? ImageFrontId { get; set; }

    public int? ImageBackId { get; set; }

    public int? ImageBodyId { get; set; }

    public string UserId { get; set; }

    public Guid VehicleId { get; set; }

    public Guid? MainDriverId { get; set; }

    public int? PolicyStatusId { get; set; }

    public Guid? SelectedProductId { get; set; }

    public short? SelectedInsuranceTypeCode { get; set; }

    public int? BankCodeId { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? SelectedLanguage { get; set; }

    public string Channel { get; set; }

    public int? InsuranceCompanyId { get; set; }

    public string InsuranceCompanyName { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? CreatedDateTime { get; set; }

    public bool? IsCancelled { get; set; }

    public DateTime? CancelationDate { get; set; }

    public string CancelledBy { get; set; }

    public bool? IsEmailVerified { get; set; }

    public Guid? AdditionalDriverIdOne { get; set; }

    public Guid? AdditionalDriverIdTwo { get; set; }

    public Guid? AdditionalDriverIdThree { get; set; }

    public Guid? AdditionalDriverIdFour { get; set; }

    public int? BankId { get; set; }

    public int? CorporateAccountId { get; set; }

    public Guid? MerchantTransactionId { get; set; }

    public bool? IsAutoleasingWallet { get; set; }

    public string DiscountCode { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public int? DiscountType { get; set; }

    public decimal? DiscountValue { get; set; }

    public string Odreference { get; set; }

    public string MainPolicyReferenceId { get; set; }

    public int? ProviderServiceId { get; set; }

    public bool Isleasing { get; set; }

    public virtual AdditionalInfo AdditionalInfo { get; set; }

    public virtual ICollection<CheckoutAdditionalDrivers> CheckoutAdditionalDrivers { get; set; } = new List<CheckoutAdditionalDrivers>();

    public virtual CheckoutCarImages ImageBack { get; set; }

    public virtual CheckoutCarImages ImageBody { get; set; }

    public virtual CheckoutCarImages ImageFront { get; set; }

    public virtual CheckoutCarImages ImageLeft { get; set; }

    public virtual CheckoutCarImages ImageRight { get; set; }

    public virtual InsuranceCompany InsuranceCompany { get; set; }

    public virtual Driver MainDriver { get; set; }

    public virtual ICollection<OrderItem> OrderItem { get; set; } = new List<OrderItem>();

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual ICollection<Policy> Policy { get; set; } = new List<Policy>();

    public virtual PolicyStatus PolicyStatus { get; set; }

    public virtual ProductType SelectedInsuranceTypeCodeNavigation { get; set; }

    public virtual Product SelectedProduct { get; set; }

    public virtual AspNetUsers User { get; set; }

    public virtual Vehicles Vehicle { get; set; }

    public virtual ICollection<PayfortPaymentRequest> PayfortPaymentRequest { get; set; } = new List<PayfortPaymentRequest>();

    public virtual ICollection<RiyadBankMigsRequest> RiyadBankMigsRequest { get; set; } = new List<RiyadBankMigsRequest>();
}