// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Clients
{
    public string Id { get; set; }

    public string Secret { get; set; }

    public string Name { get; set; }

    public int ApplicationType { get; set; }

    public bool Active { get; set; }

    public int RefreshTokenLifeTime { get; set; }

    public string AllowedOrigin { get; set; }

    public string AuthServerUrl { get; set; }

    public string RedirectUrl { get; set; }
}