// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class ClientPolicyLogDetailsSPResult
    {
        public string ReferenceId { get; set; }
        public string InsuranceCompanyName { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public int? DeductableValue { get; set; }
        public int? VehicleValue { get; set; }
        public string PolicyNo { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public string NationalId { get; set; }
    }
}
