// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Contact
{
    public int Id { get; set; }

    public string MobileNumber { get; set; }

    public string HomePhone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public virtual ICollection<InsuranceCompany> InsuranceCompany { get; set; } = new List<InsuranceCompany>();
}