// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class DeservingDiscount
{
    public int Id { get; set; }

    public string NationalId { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }
}