// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class DistanceRange
{
    public int Id { get; set; }

    public int? Code { get; set; }

    public string NameAr { get; set; }

    public string NameEn { get; set; }
}