// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class DriverLicense
{
    public int LicenseId { get; set; }

    public Guid DriverId { get; set; }

    public short? TypeDesc { get; set; }

    public string ExpiryDateH { get; set; }

    public string IssueDateH { get; set; }

    public string LicnsTypeDesc { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual LicenseType TypeDescNavigation { get; set; }
}