// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class DriverExtraLicense
{
    public int Id { get; set; }

    public Guid DriverId { get; set; }

    public short CountryCode { get; set; }

    public int? LicenseYearsId { get; set; }

    public virtual Driver Driver { get; set; }
}