// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class DriverViolation
{
    public int Id { get; set; }

    public Guid DriverId { get; set; }

    public int ViolationId { get; set; }

    public int? InsuredId { get; set; }

    public string Nin { get; set; }

    public virtual Driver Driver { get; set; }
}