// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class EdaatResponse
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UserId { get; set; }

    public string Message { get; set; }

    public string InvoiceNo { get; set; }

    public string InternalCode { get; set; }

    public int? EdaatRequestId { get; set; }

    public string Code { get; set; }

    public bool? Success { get; set; }

    public string ReferenceId { get; set; }

    public virtual EdaatRequest EdaatRequest { get; set; }
}