// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class EsalProfitMargin
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ReferenceId { get; set; }

    public string Description { get; set; }

    public bool? Applied { get; set; }

    public string ProcedureArabic { get; set; }

    public string ProcedureEnglish { get; set; }
}