// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class EsalLineItem
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ReferenceId { get; set; }

    public long? SerialNumber { get; set; }

    public string Code { get; set; }

    public string DescriptionEnglish { get; set; }

    public string DescriptionArabic { get; set; }

    public string UomEnglish { get; set; }

    public string UomArabic { get; set; }

    public decimal? Price { get; set; }

    public int? Quantity { get; set; }

    public decimal? Amount { get; set; }

    public decimal? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? AmountAfterDiscount { get; set; }

    public decimal? VatPercent { get; set; }

    public decimal? TotalVat { get; set; }

    public decimal? PriceAfterVat { get; set; }
}