// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAdditionalDriversDataResult
    {
        public string NationalId { get; set; }
        public byte? BirthDateMonth { get; set; }
        public short? BirthDateYear { get; set; }
        public int? DrivingPercentage { get; set; }
    }
}
