// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAllPoliciesForClaimsFromDBWithFilterResult
    {
        public string ReferenceId { get; set; }
        public string PolicyNo { get; set; }
        public string InsuredId { get; set; }
        public string InsuredMobileNumber { get; set; }
        public string InsuredIBAN { get; set; }
        public int? InsuredBankCode { get; set; }
        public string DriverLicenseExpiryDate { get; set; }
        public int? DriverLicenseTypeCode { get; set; }
        public Guid VehicleId { get; set; }
        public int? CompanyId { get; set; }
        public string CompanyClassTypeName { get; set; }
        public string CompanyNamespaceTypeName { get; set; }
    }
}
