// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAllRenewalPoliciesFormMessagesWithFilterResult
    {
        public string PolicyNo { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string VehicleMaker { get; set; }
        public string VehicleModel { get; set; }
        public string ExternalId { get; set; }
        public string ReferenceId { get; set; }
        public short? Plate { get; set; }
        public string SequenceNumber { get; set; }
        public string CustomCardNumber { get; set; }
        public string NIN { get; set; }
    }
}
