// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAllPoliciesInfoFromDBWithFilterResult
    {
        public string PolicyNo { get; set; }
        public string InsuranceCompanyNameEn { get; set; }
        public string InsuranceCompanyNameAr { get; set; }
        public string ReferenceNo { get; set; }
        public string NajmStatusNameEN { get; set; }
        public string NajmStatusNameAr { get; set; }
        public int InvoiceNo { get; set; }
        public string PaymentMethodNameEN { get; set; }
        public string PaymentMethodNameAr { get; set; }
    }
}
