// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAutoleasingWalletReportResult
    {
        public string ReferenceId { get; set; }
        public string PolicyNumber { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string UserAccount { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public string Method { get; set; }
        public string InsuredName { get; set; }
        public string InsuredID { get; set; }
        public decimal RemainingBalance { get; set; }
        public decimal? Amount { get; set; }
        public string PhoneNumber { get; set; }
    }
}
