// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAutoleasingCompaniesByUserIdResult
    {
        public int InsuranceCompanyID { get; set; }
        public string NameAR { get; set; }
        public string NameEN { get; set; }
        public string DescAR { get; set; }
        public string DescEN { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public Guid? ModifiedBy { get; set; }
        public int? AddressId { get; set; }
        public int? ContactId { get; set; }
        public string TEMP { get; set; }
        public string NamespaceTypeName { get; set; }
        public string ClassTypeName { get; set; }
        public string ReportTemplateName { get; set; }
        public bool isActive { get; set; }
        public string Key { get; set; }
        public string PolicyFailureRecipient { get; set; }
        public bool? IsUseNumberOfAccident { get; set; }
        public string NajmNcdFreeYearsToUseNumberOfAccident { get; set; }
        public bool? AllowAnonymousRequest { get; set; }
        public bool? ShowQuotationToUser { get; set; }
        public bool? HasDiscount { get; set; }
        public string DiscountText { get; set; }
        public DateTime? DiscountStartDate { get; set; }
        public DateTime? DiscountEndDate { get; set; }
        public bool? IsActiveTPL { get; set; }
        public bool? IsActiveComprehensive { get; set; }
        public bool? IsAddressValidationEnabled { get; set; }
        public string VAT { get; set; }
        public bool? UsePhoneCamera { get; set; }
        public string TermsAndConditionsFilePath { get; set; }
        public bool ValidateSaudiPostAddressInQuotation { get; set; }
        public int? Order { get; set; }
        public bool? IsActiveAutoleasing { get; set; }
        public string TermsAndConditionsFilePathComp { get; set; }
        public string TermsAndConditionsFilePathSanadPlus { get; set; }
        public string AutoleaseReportTemplateName { get; set; }
        public int? NajmGrade { get; set; }
        public DateTime? NajmGradeValidFrom { get; set; }
        public DateTime? NajmGradeValidTo { get; set; }
        public bool? ActiveTabbyTPL { get; set; }
        public bool? ActiveTabbyComp { get; set; }
        public bool ActiveTabbySanadPlus { get; set; }
        public bool ActiveTabbyWafiSmart { get; set; }
    }
}
