// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetAllPoliciesWithDuplicateDataResult
    {
        public string NationalId { get; set; }
        public string ReferenceId { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public string Phone { get; set; }
        public string IBAN { get; set; }
        public string Channel { get; set; }
        public string Email { get; set; }
        public string InsuredNin { get; set; }
        public string VehicleId { get; set; }
        public string FullName { get; set; }
    }
}
