// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetBulkQuotationsDetailsResult
    {
        public string InsuredNameAr { get; set; }
        public string InsuredNameEn { get; set; }
        public string InsuredNationalId { get; set; }
        public string MainDriverNameEn { get; set; }
        public string MainDriverNameAr { get; set; }
        public string DriverNationalId { get; set; }
        public string MainDriverAddressEn { get; set; }
        public string MainDriverAddressAr { get; set; }
        public int? NajmNcdFreeYears { get; set; }
        public int? VehicleValue { get; set; }
        public string VehicleMaker { get; set; }
        public short? VehicleMakerCode { get; set; }
        public string VehicleModel { get; set; }
        public long? VehicleModelCode { get; set; }
        public short? VehicleYear { get; set; }
        public string VehicleId { get; set; }
        public int? ContractDuration { get; set; }
    }
}
