// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetBcareWithdrawalListWithFilterResult
    {
        public long? Number { get; set; }
        public string Phone { get; set; }
        public string NationalId { get; set; }
        public string SequenceNumber { get; set; }
        public string FullNameEn { get; set; }
        public string FullNameAr { get; set; }
    }
}
