// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetCorporateUsersLessThan2000Result
    {
        public string UserName { get; set; }
        public decimal? Balance { get; set; }
    }
}
