// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetCompanyQuotationResponseForInitialQuoteResult
    {
        public long Id { get; set; }
        public int? RequestId { get; set; }
        public short? InsuranceTypeCode { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public int? DeductibleValue { get; set; }
        public string ReferenceId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public DateTime? CreateDateTime { get; set; }
        public string ICQuoteReferenceNo { get; set; }
        public string PromotionProgramCode { get; set; }
        public int? PromotionProgramId { get; set; }
        public long? CityId { get; set; }
        public bool? IsCheckedOut { get; set; }
        public bool AutoleasingInitialOption { get; set; }
    }
}
