// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetDriverInsuranceRecordDataResult
    {
        public string FullNameEn { get; set; }
        public string FullNameAr { get; set; }
        public string NIN { get; set; }
        public string DateOfBirth { get; set; }
        public short? ModelYear { get; set; }
        public string VehicleModel { get; set; }
        public int? VehicleValue { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public DateTime? StartDate { get; set; }
        public int? Duration { get; set; }
        public int? Remains { get; set; }
        public string ExternalId { get; set; }
        public string CustomCardNumber { get; set; }
        public string SequenceNumber { get; set; }
        public int? BankId { get; set; }
    }
}
