// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetDriverLicenseResult
    {
        public int LicenseId { get; set; }
        public Guid DriverId { get; set; }
        public short? TypeDesc { get; set; }
        public string ExpiryDateH { get; set; }
        public string IssueDateH { get; set; }
        public string licnsTypeDesc { get; set; }
    }
}
