// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetEdaatRequestsByNationalIDResult
    {
        public int Id { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UserId { get; set; }
        public bool? IsClientEnterpise { get; set; }
        public string RegistrationNo { get; set; }
        public string NationalID { get; set; }
        public string InternalCode { get; set; }
        public DateTime? IssueDate { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? TotalAmount { get; set; }
        public string Conditions { get; set; }
        public string SubBillerRegistrationNo { get; set; }
        public bool? HasValidityPeriod { get; set; }
        public string FromDurationTime { get; set; }
        public string ToDurationTime { get; set; }
        public bool? ExportToSadad { get; set; }
        public int? CompanyId { get; set; }
        public string CompanyName { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string ReferenceId { get; set; }
        public decimal? SubBillerShareAmount { get; set; }
        public decimal? SubBillerSharePercentage { get; set; }
        public string InsuredNationalId { get; set; }
    }
}
