// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetEdaatNotificationDataResult
    {
        public decimal? PaymentAmount { get; set; }
        public string PaymentDate { get; set; }
        public string ReferenceId { get; set; }
        public string InvoiceNo { get; set; }
        public string FirstNameAr { get; set; }
        public string FatherNameAr { get; set; }
        public string GrandFatherNameAr { get; set; }
        public string LastNameAr { get; set; }
        public string Email { get; set; }
        public string NationalID { get; set; }
        public string MobileNo { get; set; }
        public int? ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
    }
}
