// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetFailedPaymentTransferredOperationResult
    {
        public int? InsuranceCompanyId { get; set; }
        public string InsuranceCompanyName { get; set; }
        public int NotificationId { get; set; }
        public string BeneficiaryName { get; set; }
        public string ServiceRequest { get; set; }
        public string ReferenceId { get; set; }
    }
}
