// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetFromQuotationResponseCacheResult
    {
        public int ID { get; set; }
        public int? InsuranceCompanyId { get; set; }
        public string ExternalId { get; set; }
        public int? InsuranceTypeCode { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public int? DeductibleValue { get; set; }
        public DateTime? CreateDateTime { get; set; }
        public string QuotationResponse { get; set; }
        public Guid? UserId { get; set; }
    }
}
