// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetHyperpayRequestInfoResult
    {
        public string NationalId { get; set; }
        public string ReferenceId { get; set; }
        public int? InsuranceCompanyId { get; set; }
        public string InsuranceCompanyName { get; set; }
        public int? PolicyStatusId { get; set; }
        public string Email { get; set; }
        public string Channel { get; set; }
        public Guid? MerchantTransactionId { get; set; }
        public bool? IsEmailVerified { get; set; }
        public decimal? DiscountValue { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public decimal OrderItemPrice { get; set; }
        public string SequenceNumber { get; set; }
        public string CustomCardNumber { get; set; }
        public short? SelectedInsuranceTypeCode { get; set; }
        public string ODReference { get; set; }
    }
}
