// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetIInsuredByNationalIdResult
    {
        public int Id { get; set; }
        public string NationalId { get; set; }
        public int CardIdTypeId { get; set; }
        public DateTime BirthDate { get; set; }
        public string BirthDateH { get; set; }
        public int? GenderId { get; set; }
        public string NationalityCode { get; set; }
        public long? IdIssueCityId { get; set; }
        public string FirstNameAr { get; set; }
        public string MiddleNameAr { get; set; }
        public string LastNameAr { get; set; }
        public string FirstNameEn { get; set; }
        public string MiddleNameEn { get; set; }
        public string LastNameEn { get; set; }
        public int? SocialStatusId { get; set; }
        public int? OccupationId { get; set; }
        public string ResidentOccupation { get; set; }
        public int EducationId { get; set; }
        public int? ChildrenBelow16Years { get; set; }
        public long? WorkCityId { get; set; }
        public long? CityId { get; set; }
        public DateTime? CreatedDateTime { get; set; }
        public DateTime? ModifiedDateTime { get; set; }
        public long? UserSelectedWorkCityId { get; set; }
        public long? UserSelectedCityId { get; set; }
        public int? AddressId { get; set; }
        public string OccupationCode { get; set; }
        public string OccupationName { get; set; }
    }
}
