// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetIntialQuotationResult
    {
        public string VehicleMaker { get; set; }
        public string VehicleModel { get; set; }
        public short? ModelYear { get; set; }
        public int? vehiclevalue { get; set; }
        public string Fullname { get; set; }
        public string NIN { get; set; }
        public string BirthDate { get; set; }
        public string BirthMonth { get; set; }
        public string Birthyear { get; set; }
        public DateTime? RequestPolicyEffectiveDate { get; set; }
        public string MobileNumber { get; set; }
        public int? DeductibleValue { get; set; }
        public string RepairMethod { get; set; }
        public string ExternalId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ContractDuration { get; set; }
        public bool AutoleasingInitialOption { get; set; }
        public short? VehicleMakerCode { get; set; }
        public int? CompanyName { get; set; }
    }
}
