// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetLeasingShoppingCartItemDBResult
    {
        public string UserId { get; set; }
        public string ReferenceId { get; set; }
        public Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public string ProductNameAr { get; set; }
        public string ProductNameEn { get; set; }
        public decimal ProductPrice { get; set; }
        public short? InsuranceTypeCode { get; set; }
        public string InsuranceCompanyKey { get; set; }
        public int InsuranceCompanyID { get; set; }
        public string InsuranceCompanyNameAR { get; set; }
        public string InsuranceCompanyNameEN { get; set; }
        public bool? IsAddressValidationEnabled { get; set; }
        public long QuotationResponseId { get; set; }
        public DateTime? QuotationResponseCreateDateTime { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public int? DeductibleValue { get; set; }
        public string QuotationReferenceId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int? ProductInsuranceTypeCode { get; set; }
    }
}
