// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetleasingprofilePolicyDataResult
    {
        public short? VehicleMakerCode { get; set; }
        public string VehicleMaker { get; set; }
        public string CarPlateText1 { get; set; }
        public string CarPlateText2 { get; set; }
        public string CarPlateText3 { get; set; }
        public short? CarPlateNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string PolicyNo { get; set; }
        public string ReferenceId { get; set; }
        public int VehicleIdTypeId { get; set; }
        public string CustomCardNumber { get; set; }
        public string SequenceNumber { get; set; }
        public string ConvertedCarPlateText1 { get; set; }
        public string ConvertedCarPlateText2 { get; set; }
        public string ConvertedCarPlateText3 { get; set; }
        public short? ConvertedCarPlateNumber { get; set; }
    }
}
