// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetLastPruchasedCheckoutDetailsByNINResult
    {
        public string ReferenceId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string IBAN { get; set; }
        public int? ImageRightId { get; set; }
        public int? ImageLeftId { get; set; }
        public int? ImageFrontId { get; set; }
        public int? ImageBackId { get; set; }
        public int? ImageBodyId { get; set; }
        public string UserId { get; set; }
        public Guid VehicleId { get; set; }
        public Guid? MainDriverId { get; set; }
        public int? PolicyStatusId { get; set; }
        public Guid? SelectedProductId { get; set; }
        public short? SelectedInsuranceTypeCode { get; set; }
        public int? bankCodeId { get; set; }
        public int? PaymentMethodId { get; set; }
        public int? SelectedLanguage { get; set; }
        public string Channel { get; set; }
        public int? InsuranceCompanyId { get; set; }
        public string InsuranceCompanyName { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? CreatedDateTime { get; set; }
        public bool? IsCancelled { get; set; }
        public DateTime? CancelationDate { get; set; }
        public string CancelledBy { get; set; }
        public bool? IsEmailVerified { get; set; }
        public Guid? AdditionalDriverIdOne { get; set; }
        public Guid? AdditionalDriverIdTwo { get; set; }
        public Guid? AdditionalDriverIdThree { get; set; }
        public Guid? AdditionalDriverIdFour { get; set; }
        public int? BankId { get; set; }
        public int? CorporateAccountId { get; set; }
        public Guid? MerchantTransactionId { get; set; }
        public bool? IsAutoleasingWallet { get; set; }
        public string DiscountCode { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public int? DiscountType { get; set; }
        public decimal? DiscountValue { get; set; }
        public string ODReference { get; set; }
        public string MainPolicyReferenceId { get; set; }
        public int? ProviderServiceId { get; set; }
        public bool Isleasing { get; set; }
    }
}
