// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetLeasingProfileBasicDataResult
    {
        public int LeasingUserId { get; set; }
        public string Email { get; set; }
        public string UpdatedEmail { get; set; }
        public string PhoneNumber { get; set; }
        public Guid VehicleId { get; set; }
        public string VehicleMaker { get; set; }
        public string ChassisNumber { get; set; }
        public Guid? PolicyFileId { get; set; }
        public string FullNameAr { get; set; }
        public string FullNameEn { get; set; }
        public string NIN { get; set; }
        public string ReferenceId { get; set; }
        public string PolicyNo { get; set; }
        public string ExternalId { get; set; }
        public Guid ProductId { get; set; }
        public int? InsuredBankCode { get; set; }
        public string DriverLicenseExpiryDate { get; set; }
        public short? DriverLicenseTypeCode { get; set; }
        public int CompanyId { get; set; }
        public string CompanyClassTypeName { get; set; }
        public string CompanyNamespaceTypeName { get; set; }
        public string Iban { get; set; }
        public string ParentExternalId { get; set; }
        public string ParentReferenceId { get; set; }
    }
}
