// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetNajmAverageResponseTimeResult
    {
        public double? AverageResponseTime { get; set; }
        public int? CompanyId { get; set; }
        public string CompanyAr { get; set; }
        public string CompanyEn { get; set; }
        public int? NajmGrade { get; set; }
        public DateTime? NajmGradeValidFrom { get; set; }
        public DateTime? NajmGradeValidTo { get; set; }
    }
}
