// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetOldPolicyDataResult
    {
        public int Id { get; set; }
        public int? InsuranceCompanyID { get; set; }
        public byte StatusCode { get; set; }
        public string PolicyNo { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public string CheckOutDetailsId { get; set; }
        public Guid? PolicyFileId { get; set; }
        public string NajmStatus { get; set; }
        public bool IsRefunded { get; set; }
        public int NajmStatusId { get; set; }
        public bool? IsCancelled { get; set; }
        public DateTime? CancelationDate { get; set; }
        public string CancelledBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public double? NajmResponseTimeInSeconds { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? NotificationNo { get; set; }
        public bool? IsRenewed { get; set; }
        public string RenewalNotificationStatus { get; set; }
    }
}
