// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetPolicyRequestTimeResult
    {
        public string NameEN { get; set; }
        public string NameAR { get; set; }
        public string PolicyNo { get; set; }
        public double? NajmResponseTimeInSeconds { get; set; }
    }
}
