// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetPriceDetailsByProductIdsListResult
    {
        public Guid DetailId { get; set; }
        public Guid ProductID { get; set; }
        public byte PriceTypeCode { get; set; }
        public decimal PriceValue { get; set; }
        public decimal? PercentageValue { get; set; }
        public DateTime? CreateDateTime { get; set; }
        public bool? IsCheckedOut { get; set; }
    }
}
