// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetProductDetailsResult
    {
        public string ReferenceId { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public Guid ProductId { get; set; }
        public byte PriceTypeCode { get; set; }
        public decimal PriceValue { get; set; }
        public decimal? PercentageValue { get; set; }
    }
}
