// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetPolicyInformationForMorniResult
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string NationalId { get; set; }
        public string PlanReferenceNumber { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string PolicyNumber { get; set; }
        public string PolicyType { get; set; }
        public string ReferenceId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public short? Year { get; set; }
        public string Color { get; set; }
        public short? PlateNumber { get; set; }
        public string PlateFirstLetterId { get; set; }
        public string PlateSecondLetterId { get; set; }
        public string PlateThirdLetterId { get; set; }
        public string VIN { get; set; }
        public string SequenceNumber { get; set; }
        public string CustomsNumber { get; set; }
    }
}
