// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetQuotationsFormDetailsByExternalIdResult
    {
        public string VehicleOwnerNameAr { get; set; }
        public string VehicleOwnerNameEn { get; set; }
        public string InsuredNationalId { get; set; }
        public string DriverNameEn { get; set; }
        public string DriverNameAr { get; set; }
        public string DriverNIN { get; set; }
        public string DriverAddressEn { get; set; }
        public string DriverAddressAr { get; set; }
        public int? VehicleValue { get; set; }
        public string VehicleMaker { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleId { get; set; }
        public string AnnualDepreciationPercentage { get; set; }
        public int? NCDFreeYears { get; set; }
    }
}
