// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetQuotationRequestDataDBResult
    {
        public int ID { get; set; }
        public string ExternalId { get; set; }
        public long CityCode { get; set; }
        public DateTime? RequestPolicyEffectiveDate { get; set; }
        public int? NajmNcdFreeYears { get; set; }
        public string NajmNcdRefrence { get; set; }
        public int? NoOfAccident { get; set; }
        public string NajmResponse { get; set; }
        public string MajorColor { get; set; }
        public int VehicleIdTypeId { get; set; }
        public short? CarPlateNumber { get; set; }
        public string CarPlateText1 { get; set; }
        public string CarPlateText2 { get; set; }
        public string CarPlateText3 { get; set; }
        public string CarOwnerNIN { get; set; }
        public string CarOwnerName { get; set; }
        public byte? PlateTypeCode { get; set; }
        public string LicenseExpiryDate { get; set; }
        public string SequenceNumber { get; set; }
        public string CustomCardNumber { get; set; }
        public short? ModelYear { get; set; }
        public string VehicleMaker { get; set; }
        public short? VehicleMakerCode { get; set; }
        public string VehicleModel { get; set; }
        public long? VehicleModelCode { get; set; }
        public byte VehicleBodyCode { get; set; }
        public string RegisterationPlace { get; set; }
        public int VehicleLoad { get; set; }
        public byte? Cylinders { get; set; }
        public int VehicleWeight { get; set; }
        public bool OwnerTransfer { get; set; }
        public bool? IsUsedCommercially { get; set; }
        public int? VehicleValue { get; set; }
        public decimal? CurrentMileageKM { get; set; }
        public int? AxleWeightId { get; set; }
        public bool HasModifications { get; set; }
        public int? ParkingLocationId { get; set; }
        public int? EngineSizeId { get; set; }
        public int? TransmissionTypeId { get; set; }
        public string ModificationDetails { get; set; }
        public string ChassisNumber { get; set; }
        public int? MileageExpectedAnnualId { get; set; }
        public int VehicleUseId { get; set; }
        public int InsuredId { get; set; }
        public int CardIdTypeId { get; set; }
        public string NationalId { get; set; }
        public DateTime BirthDate { get; set; }
        public string BirthDateH { get; set; }
        public int? GenderId { get; set; }
        public string NationalityCode { get; set; }
        public string FirstNameAr { get; set; }
        public string MiddleNameAr { get; set; }
        public string LastNameAr { get; set; }
        public string FirstNameEN { get; set; }
        public string MiddleNameEn { get; set; }
        public string LastNameEN { get; set; }
        public int? SocialStatusId { get; set; }
        public int EducationId { get; set; }
        public int? ChildrenBelow16Years { get; set; }
        public int? OccupationId { get; set; }
        public string CityArabicDescription { get; set; }
        public long? CityYakeenCode { get; set; }
        public string IdIssueCityArabicDescription { get; set; }
        public long? IdIssueCityYakeenCode { get; set; }
        public string WorkCityArabicDescription { get; set; }
        public long? WorkCityYakeenCode { get; set; }
        public string OccupationCode { get; set; }
        public string OccupationNameAr { get; set; }
        public string OccupationNameEn { get; set; }
        public string NIN { get; set; }
        public bool? IsSpecialNeed { get; set; }
        public int? NOALast5Years { get; set; }
        public int? NOCLast5Years { get; set; }
        public int? NCDFreeYears { get; set; }
        public string NCDReference { get; set; }
        public int? DrivingPercentage { get; set; }
        public int? MedicalConditionId { get; set; }
    }
}
