// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetQuotationDetailsByReferenceIdResult
    {
        public Guid DriverId { get; set; }
        public string InsuredNationalId { get; set; }
        public string DriverNin { get; set; }
        public DateTime? CreateDateTime { get; set; }
        public string CompanyKey { get; set; }
        public int InsuranceCompanyID { get; set; }
    }
}
