// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetSamaReportResult
    {
        public string ReferenceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public int BcareInvoiceNumber { get; set; }
        public string SCHEME { get; set; }
        public string PolicyHolder { get; set; }
        public string Mob { get; set; }
        [Column("Account Mob")]
        public string AccountMob { get; set; }
        public string Email { get; set; }
        [Column("Account Email")]
        public string AccountEmail { get; set; }
        public string Insurer { get; set; }
        public string PolicyNo { get; set; }
        public string PaymentMethod { get; set; }
        public string CardNumber { get; set; }
        public string InsuranceProduct { get; set; }
        public decimal? ExtraPremiumPrice { get; set; }
        public decimal? Vat { get; set; }
        public decimal? ProductPrice { get; set; }
        public decimal? TotalPrice { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Fees { get; set; }
        public decimal? TotalBCareFees { get; set; }
        public decimal? TotalBCareCommission { get; set; }
        public decimal? TotalCompanyAmount { get; set; }
        public string InsuranceCompanyName { get; set; }
        public int InsuranceCompanyId { get; set; }
        public DateTime? DriverBirthDate { get; set; }
        public string NationalId { get; set; }
        public string IBAN { get; set; }
        public string Channel { get; set; }
        public string AdditionalDriverOneNIN { get; set; }
        public string AdditionalDriverOneName { get; set; }
        public string AdditionalDriverTwoNIN { get; set; }
        public string AdditionalDriverTwoName { get; set; }
        public string AdditionalDriverThreeNIN { get; set; }
        public string AdditionalDriverThreeName { get; set; }
        public string AdditionalDriverFourNIN { get; set; }
        public string AdditionalDriverFourName { get; set; }
        public int? NajmNcdFreeYears { get; set; }
        public int? NoOfAccident { get; set; }
        public string ChassisNumber { get; set; }
        public string EnglishBankName { get; set; }
        public string ArabicBankName { get; set; }
        public string CarOwnerNIN { get; set; }
        public string InsuredNationalId { get; set; }
        public byte VehicleBodyCode { get; set; }
        public string ArabicVehicleBody { get; set; }
        public string EnglishVehicleBody { get; set; }
        public Guid? MerchantTransactionId { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public decimal? TotalBCareDiscount { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public string DiscountCode { get; set; }
        public decimal? DiscountValue { get; set; }
        public decimal? BasicPrice { get; set; }
        public decimal? PaidAmount { get; set; }
        public decimal? ActualBankFees { get; set; }
        public string FeesCalculationDetails { get; set; }
    }
}
