// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetShadowAccountDetailsResult
    {
        public string DriverId { get; set; }
        public string CustomCardNumber { get; set; }
        public string SequenceNumber { get; set; }
        public int? NumberOfPolicies { get; set; }
        public decimal? TotalAmmount { get; set; }
        public decimal? ShadowAccount { get; set; }
    }
}
