// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetUserActivePoliciesCountResult
    {
        public int HasActivePolicy { get; set; }
        public DateTime? ExpiryDate { get; set; }
    }
}
