// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetUserAddressesResult
    {
        public string NationalId { get; set; }
        public string ArabicCity { get; set; }
        public string EnglishCity { get; set; }
        public string ArabicFullName { get; set; }
        public string EnglishcFullName { get; set; }
    }
}
