// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetUserPromotionProgramInfo1Result
    {
        public string NationalId { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public int? PromotionProgramId { get; set; }
    }
}
