// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetUserPromotionProgramResult
    {
        public int Id { get; set; }
        public int? PromotionProgramId { get; set; }
        public string Code { get; set; }
        public int InsuranceCompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatorId { get; set; }
        public string ModifierId { get; set; }
        public short InsuranceTypeCode { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }
    }
}
