// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetUserSuccessPoliciesInfoResult
    {
        public string NationalId { get; set; }
        public bool? IsCompany { get; set; }
        public int? PolicyStatusId { get; set; }
        public string ReferenceId { get; set; }
        public DateTime? CreatedDateTime { get; set; }
    }
}
