// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetVehiclesByNinResult
    {
        public string SequenceNumber { get; set; }
        public string CustomCardNumber { get; set; }
        public string MakerAr { get; set; }
        public string MakerEn { get; set; }
        public string ModelAr { get; set; }
        public string ModelEn { get; set; }
        public short? ModelYear { get; set; }
    }
}
