// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetVehicleSuccessPoliciesWithFilterForAddBenefitsResult
    {
        public string ReferenceId { get; set; }
        public string policyNo { get; set; }
        public string insuredNIN { get; set; }
        public DateTime? policyIssueDate { get; set; }
        public string InsuranceCompanyNameAr { get; set; }
        public string InsuranceCompanyNameEn { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
    }
}
