// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class GetWareefItemsDetailsResult
    {
        public int Id { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string ImageBytes { get; set; }
        public string ItemURl { get; set; }
        public int? WareefCategoryId { get; set; }
        public string CategoryAR { get; set; }
        public string CategoryEN { get; set; }
    }
}
