// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class HyperPayNotificationTransactions
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UniqueId { get; set; }

    public decimal? PayoutTransferAmount { get; set; }

    public string MerchantTransactionId { get; set; }

    public int NotificationId { get; set; }
}