// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class InsuranceCompany
{
    public int InsuranceCompanyId { get; set; }

    public string NameAr { get; set; }

    public string NameEn { get; set; }

    public string DescAr { get; set; }

    public string DescEn { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public int? AddressId { get; set; }

    public int? ContactId { get; set; }

    public string Temp { get; set; }

    public string NamespaceTypeName { get; set; }

    public string ClassTypeName { get; set; }

    public string ReportTemplateName { get; set; }

    public bool? IsActive { get; set; }

    public string Key { get; set; }

    public string PolicyFailureRecipient { get; set; }

    public bool? IsUseNumberOfAccident { get; set; }

    public string NajmNcdFreeYearsToUseNumberOfAccident { get; set; }

    public bool? AllowAnonymousRequest { get; set; }

    public bool? ShowQuotationToUser { get; set; }

    public bool? HasDiscount { get; set; }

    public string DiscountText { get; set; }

    public DateTime? DiscountStartDate { get; set; }

    public DateTime? DiscountEndDate { get; set; }

    public bool? IsActiveTpl { get; set; }

    public bool? IsActiveComprehensive { get; set; }

    public bool? IsAddressValidationEnabled { get; set; }

    public string Vat { get; set; }

    public bool? UsePhoneCamera { get; set; }

    public string TermsAndConditionsFilePath { get; set; }

    public bool ValidateSaudiPostAddressInQuotation { get; set; }

    public int? Order { get; set; }

    public bool? IsActiveAutoleasing { get; set; }

    public string TermsAndConditionsFilePathComp { get; set; }

    public string TermsAndConditionsFilePathSanadPlus { get; set; }

    public string AutoleaseReportTemplateName { get; set; }

    public int? NajmGrade { get; set; }

    public DateTime? NajmGradeValidFrom { get; set; }

    public DateTime? NajmGradeValidTo { get; set; }

    public bool? ActiveTabbyTpl { get; set; }

    public bool? ActiveTabbyComp { get; set; }

    public bool? ActiveTabbySanadPlus { get; set; }

    public bool? ActiveTabbyWafiSmart { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<CheckoutDetails> CheckoutDetails { get; set; } = new List<CheckoutDetails>();

    public virtual Contact Contact { get; set; }

    public virtual ICollection<Deductible> Deductible { get; set; } = new List<Deductible>();

    public virtual ICollection<InsuaranceCompanyBenefit> InsuaranceCompanyBenefit { get; set; } = new List<InsuaranceCompanyBenefit>();

    public virtual ICollection<Invoice> Invoice { get; set; } = new List<Invoice>();

    public virtual ICollection<Policy> Policy { get; set; } = new List<Policy>();

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();

    public virtual ICollection<PromotionProgramCode> PromotionProgramCode { get; set; } = new List<PromotionProgramCode>();

    public virtual ICollection<QuotationResponse> QuotationResponse { get; set; } = new List<QuotationResponse>();

    public virtual ICollection<QuotationResponseNew> QuotationResponseNew { get; set; } = new List<QuotationResponseNew>();

    public virtual ICollection<UserPurchasedPromotionPrograms> UserPurchasedPromotionPrograms { get; set; } = new List<UserPurchasedPromotionPrograms>();
}