// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class InsuredAddressesCount
{
    public int Id { get; set; }

    public string NationalId { get; set; }

    public int? YakeenAddressesCount { get; set; }

    public DateTime? CreatedDate { get; set; }
}