// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class InsuredExtraLicenses
{
    public int Id { get; set; }

    public int InsuredId { get; set; }

    public string DriverNin { get; set; }

    public bool IsMainDriver { get; set; }

    public int LicenseNumberYears { get; set; }

    public short LicenseCountryCode { get; set; }

    public DateTime? CreatedDate { get; set; }
}