// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class InsuaranceCompanyBenefit
{
    public Guid BenefitId { get; set; }

    public int InsurnaceCompanyId { get; set; }

    public short BenefitCode { get; set; }

    public decimal BenefitPrice { get; set; }

    public virtual Benefit BenefitCodeNavigation { get; set; }

    public virtual InsuranceCompany InsurnaceCompany { get; set; }
}