// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class IntegrationTransactionToBeDeleted
{
    public int Id { get; set; }

    public Guid? MessageId { get; set; }

    public string Method { get; set; }

    public string InputParams { get; set; }

    public string OutputResults { get; set; }

    public int? Status { get; set; }

    public DateTime? TransactionDate { get; set; }
}