// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class InvoiceBenefit
{
    public int Id { get; set; }

    public int? InvoiceId { get; set; }

    public short? BenefitId { get; set; }

    public decimal? BenefitPrice { get; set; }

    public virtual Benefit Benefit { get; set; }

    public virtual Invoice Invoice { get; set; }
}