// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class LeasingVerifyUsers
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string VerificationCode { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsVerified { get; set; }

    public string MethodName { get; set; }
}