// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Logger
{
    public Guid Id { get; set; }

    public string StackTrace { get; set; }

    public string Message { get; set; }

    public string ExceptionAsString { get; set; }

    public DateTime? ExceptionDate { get; set; }

    public string Key { get; set; }

    public int? Level { get; set; }
}