// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class MigrationHistory
{
    public string MigrationId { get; set; }

    public string ContextKey { get; set; }

    public byte[] Model { get; set; }

    public string ProductVersion { get; set; }
}