// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class MobileAppVersions
{
    public int Id { get; set; }

    public string Version { get; set; }

    public string DescriptionAr { get; set; }

    public string DescriptionEn { get; set; }

    public DateTime CreationDate { get; set; }

    public string Platform { get; set; }

    public string Url { get; set; }
}