// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Moidetail
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Email { get; set; }

    public string FileName { get; set; }

    public byte[] FileByteArray { get; set; }

    public string FileMimeType { get; set; }

    public bool? Approved { get; set; }

    public DateTime? CreatedAt { get; set; }
}