// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class NajmStatusHistory
{
    public int Id { get; set; }

    public string ReferenceId { get; set; }

    public string PolicyNo { get; set; }

    public int StatusCode { get; set; }

    public string StatusDescription { get; set; }

    public DateTime? UploadedDate { get; set; }

    public string UploadedReference { get; set; }
}