// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class NajmResponse
{
    public int Id { get; set; }

    public int? IsVehicleRegistered { get; set; }

    public string PolicyHolderNin { get; set; }

    public string VehicleId { get; set; }

    public string Ncdreference { get; set; }

    public int? NcdfreeYears { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsDeleted { get; set; }
}