// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Nationality
{
    public int Id { get; set; }

    public double? Code { get; set; }

    public string EnglishDescription { get; set; }

    public string ArabicDescription { get; set; }
}