// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class NotificationParameter
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public int NotificationId { get; set; }

    public virtual Notification Notification { get; set; }
}