// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Occupation
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string NameAr { get; set; }

    public string NameEn { get; set; }

    public bool? IsCitizen { get; set; }

    public bool? IsMale { get; set; }

    public virtual ICollection<Driver> Driver { get; set; } = new List<Driver>();

    public virtual ICollection<Insured> Insured { get; set; } = new List<Insured>();
}