// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class OrderItem
{
    public int Id { get; set; }

    public string CheckoutDetailReferenceId { get; set; }

    public Guid ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual CheckoutDetails CheckoutDetailReference { get; set; }

    public virtual ICollection<OrderItemBenefit> OrderItemBenefit { get; set; } = new List<OrderItemBenefit>();
}