// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class PayfortPaymentRequest
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public decimal? Amount { get; set; }

    public string ReferenceNumber { get; set; }

    public bool? IsCancelled { get; set; }

    public DateTime? CancelationDate { get; set; }

    public string CancelledBy { get; set; }

    public virtual ICollection<PayfortPaymentResponse> PayfortPaymentResponse { get; set; } = new List<PayfortPaymentResponse>();

    public virtual ICollection<CheckoutDetails> Checkoutdetails { get; set; } = new List<CheckoutDetails>();

    public virtual ICollection<PolicyUpdateRequest> PolicyUpdateRequest { get; set; } = new List<PolicyUpdateRequest>();
}