// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Payment
{
    public int BillNumber { get; set; }

    public string ReferenceId { get; set; }

    public string UserId { get; set; }

    public string Ibna { get; set; }

    public int? BankCode { get; set; }

    public int? PaymentStatus { get; set; }
}