// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Policy
{
    public int Id { get; set; }

    public int? InsuranceCompanyId { get; set; }

    public byte StatusCode { get; set; }

    public string PolicyNo { get; set; }

    public DateTime? PolicyIssueDate { get; set; }

    public DateTime? PolicyEffectiveDate { get; set; }

    public DateTime? PolicyExpiryDate { get; set; }

    public string CheckOutDetailsId { get; set; }

    public Guid? PolicyFileId { get; set; }

    public string NajmStatus { get; set; }

    public bool IsRefunded { get; set; }

    public int NajmStatusId { get; set; }

    public bool? IsCancelled { get; set; }

    public DateTime? CancelationDate { get; set; }

    public string CancelledBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public double? NajmResponseTimeInSeconds { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? NotificationNo { get; set; }

    public bool? IsRenewed { get; set; }

    public string RenewalNotificationStatus { get; set; }

    public virtual CheckoutDetails CheckOutDetails { get; set; }

    public virtual InsuranceCompany InsuranceCompany { get; set; }

    public virtual ICollection<Invoice> Invoice { get; set; } = new List<Invoice>();

    public virtual NajmStatus NajmStatusNavigation { get; set; }

    public virtual PolicyDetails PolicyDetails { get; set; }

    public virtual PolicyFile PolicyFile { get; set; }

    public virtual ICollection<PolicyUpdateRequest> PolicyUpdateRequest { get; set; } = new List<PolicyUpdateRequest>();
}