// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class PolicyUpdateRequestAttachment
{
    public int Id { get; set; }

    public int PolicyUpdReqId { get; set; }

    public int AttachmentId { get; set; }

    public int AttachmentTypeId { get; set; }

    public virtual Attachment Attachment { get; set; }

    public virtual PolicyUpdateRequest PolicyUpdReq { get; set; }
}