// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class PolicyRenewedByCompany
{
    public int Id { get; set; }

    public string ReferenceId { get; set; }

    public string OldPolicyNo { get; set; }

    public string NewPolicyNo { get; set; }

    public int ProductTypeCode { get; set; }

    public string RenewalDate { get; set; }

    public decimal PolicyAmount { get; set; }

    public decimal PolicyVat { get; set; }

    public decimal PolicyTotalAmount { get; set; }

    public decimal PolicyRenewalCommission { get; set; }

    public Guid? VehicleId { get; set; }

    public string SequanceNo { get; set; }

    public int? InsuranceCompanyId { get; set; }
}