// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class policyInfoForODResult
    {
        public string PolicyNo { get; set; }
        public DateTime? PolicyExpiryDate { get; set; }
        public string Phone { get; set; }
        public string ExternalId { get; set; }
        public int? SelectedLanguage { get; set; }
    }
}
