// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class PolicyFile
{
    public Guid Id { get; set; }

    public byte[] PolicyFileByte { get; set; }

    public string FilePath { get; set; }

    public string ServerIp { get; set; }

    public virtual ICollection<Policy> Policy { get; set; } = new List<Policy>();
}