// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class PolicyUpdateRequest
{
    public int Id { get; set; }

    public int? PolicyId { get; set; }

    public int RequestTypeId { get; set; }

    public int StatusId { get; set; }

    public string Guid { get; set; }

    public virtual Policy Policy { get; set; }

    public virtual ICollection<PolicyUpdatePayment> PolicyUpdatePayment { get; set; } = new List<PolicyUpdatePayment>();

    public virtual ICollection<PolicyUpdateRequestAttachment> PolicyUpdateRequestAttachment { get; set; } = new List<PolicyUpdateRequestAttachment>();

    public virtual ICollection<PayfortPaymentRequest> PayfortPaymentRequest { get; set; } = new List<PayfortPaymentRequest>();
}