// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class ProductDriver
{
    public int Id { get; set; }

    public Guid ProductId { get; set; }

    public Guid DriverId { get; set; }

    public decimal DriverPrice { get; set; }

    public string DriverExternalId { get; set; }
}