// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class ProfileNotification
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string DescriptionAr { get; set; }

    public string DescriptionEn { get; set; }

    public int? TypeId { get; set; }

    public int? ModuleId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? TicketStatusId { get; set; }
}