// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class QuotationRequestAdditionalDrivers
{
    public int QuotationRequestId { get; set; }

    public Guid AdditionalDriverId { get; set; }

    public byte? AdditionalDriverRelationShipId { get; set; }

    public virtual Driver AdditionalDriver { get; set; }

    public virtual QuotationRequest QuotationRequest { get; set; }
}