// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Region
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<City> City { get; set; } = new List<City>();
}