// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class RenwalStatitics_OldTableResult
    {
        public string parentExternalId { get; set; }
        public string parentReferenceId { get; set; }
        public string ReferenceId { get; set; }
        public string ExternalId { get; set; }
        public string SequenceNumber { get; set; }
        public decimal? TotalPrice { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UserId { get; set; }
        public bool? isDeleted { get; set; }
    }
}
