// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class RoleType
{
    public Guid Id { get; set; }

    public string TypeNameAr { get; set; }

    public string TypeNameEn { get; set; }

    public virtual ICollection<Role> Role { get; set; } = new List<Role>();
}