// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Role
{
    public Guid Id { get; set; }

    public Guid RoleTypeId { get; set; }

    public string RoleNameAr { get; set; }

    public string RoleNameEn { get; set; }

    public virtual ICollection<AspNetUsers> AspNetUsers { get; set; } = new List<AspNetUsers>();

    public virtual RoleType RoleType { get; set; }
}