// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class SadadResponse
{
    public int Id { get; set; }

    public int SadadRequestId { get; set; }

    public string Status { get; set; }

    public int ErrorCode { get; set; }

    public string Description { get; set; }

    public int TrackingId { get; set; }

    public virtual SadadRequest SadadRequest { get; set; }
}