// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class SadadRequest
{
    public int Id { get; set; }

    public int BillerId { get; set; }

    public int ExactFlag { get; set; }

    public string CustomerAccountNumber { get; set; }

    public string CustomerAccountName { get; set; }

    public decimal BillAmount { get; set; }

    public DateTime BillOpenDate { get; set; }

    public DateTime BillDueDate { get; set; }

    public DateTime BillExpiryDate { get; set; }

    public DateTime BillCloseDate { get; set; }

    public decimal? BillMaxAdvanceAmount { get; set; }

    public decimal? BillMinAdvanceAmount { get; set; }

    public decimal? BillMinPartialAmount { get; set; }

    public bool? IsActive { get; set; }

    public int? CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string ReferenceId { get; set; }

    public virtual ICollection<SadadResponse> SadadResponse { get; set; } = new List<SadadResponse>();
}