// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class SamaStatisticsCountReportResult
    {
        public string Item { get; set; }
        public int? TotalIndividualPoliciesTPLSandWafi_Male { get; set; }
    }
}
