// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class SendNotificationLogs
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Input { get; set; }

    public int? ErrorCode { get; set; }

    public string ErrorDescription { get; set; }

    public DateTime CreationDate { get; set; }
}