// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class Setting
{
    public int Id { get; set; }

    public int? MaxNumberOfPolicies { get; set; }

    public int? MaxNumberOfPromotionCode { get; set; }
}