// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class ShoppingCartItem
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public Guid ProductId { get; set; }

    public int Quantity { get; set; }

    public string ReferenceId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }
}