// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class SmsCodes
{
    public int Id { get; set; }

    public string Mobile { get; set; }

    public string Code { get; set; }

    public bool IsVerified { get; set; }

    public DateTime? CreatedDate { get; set; }
}