// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class SmsproviderSettings
{
    public int Id { get; set; }

    public string Method { get; set; }

    public string Module { get; set; }

    public string Smsprovider { get; set; }
}