// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Domain.DomainEntities.Entities.DomainEntities
{
    public partial class SuccessPolicystatisticsResult
    {
        public string PolicyNo { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? PolicyEffectiveDate { get; set; }
        public string Phone { get; set; }
        public string StatusAR { get; set; }
        public string StatusEn { get; set; }
        public string Email { get; set; }
        public string AddtionalDriverOne { get; set; }
        public string AddtionalDriverTwo { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public byte[] ImageBack { get; set; }
        public byte[] ImageBody { get; set; }
        public byte[] ImageFront { get; set; }
        public byte[] ImageLeft { get; set; }
        public byte[] ImageRight { get; set; }
        public string CompanyNameAr { get; set; }
        public string CompanyNameEn { get; set; }
        public string InsuredNameAr { get; set; }
        public string InsuredNameEn { get; set; }
        public string plateText { get; set; }
        public string VehicleModel { get; set; }
        public bool? VehicleAgencyRepair { get; set; }
        public string CustomCardNumber { get; set; }
        public string SequenceNumber { get; set; }
        public bool OwnerTransfer { get; set; }
        public short? CarPlateNumber { get; set; }
        public decimal? Fees { get; set; }
        public decimal? Discount { get; set; }
        public string ReferenceId { get; set; }
        public decimal? ProductPrice { get; set; }
        public decimal? ExtraPremiumPrice { get; set; }
        public decimal? TotalPrice { get; set; }
        public decimal? SubTotalPrice { get; set; }
        public int InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public decimal? Vat { get; set; }
        public string NIN { get; set; }
    }
}
