// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class TabbyRequests
{
    public Guid Id { get; set; }

    public double? Amount { get; set; }

    public string Currency { get; set; }

    public string RefrenceId { get; set; }

    public string UserId { get; set; }

    public string Channel { get; set; }

    public DateTime? CreatedDate { get; set; }

    public double? InsuranceCompanyAmount { get; set; }

    public int? CompanyId { get; set; }

    public string CompanyName { get; set; }

    public virtual ICollection<TabbyCaptureRequests> TabbyCaptureRequests { get; set; } = new List<TabbyCaptureRequests>();

    public virtual ICollection<TabbyNotifications> TabbyNotifications { get; set; } = new List<TabbyNotifications>();

    public virtual ICollection<TabbyRequestDetails> TabbyRequestDetails { get; set; } = new List<TabbyRequestDetails>();

    public virtual ICollection<TabbyResponses> TabbyResponses { get; set; } = new List<TabbyResponses>();

    public virtual ICollection<TabbyWebHooks> TabbyWebHooks { get; set; } = new List<TabbyWebHooks>();
}