// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class TabbyWebHookDetails
{
    public long Id { get; set; }

    public long TabbyWebHookId { get; set; }

    public string Buyer { get; set; }

    public string ShippingAddress { get; set; }

    public string Order { get; set; }

    public string BuyerHistory { get; set; }

    public string OrderHistory { get; set; }

    public string Refunds { get; set; }

    public string Captures { get; set; }

    public string Meta { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual TabbyWebHooks TabbyWebHook { get; set; }
}