// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class TawuniyaTempTable
{
    public int Id { get; set; }

    public string QtServiceRequestMessage { get; set; }

    public string PorposalResponse { get; set; }

    public string ReferenceId { get; set; }
}