// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class TawuniyaProposal
{
    public int Id { get; set; }

    public string ProposalNumber { get; set; }

    public string ReferenceId { get; set; }

    public int? ProposalTypeCode { get; set; }
}