// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserClaim
{
    public int Id { get; set; }

    public string ReferenceId { get; set; }

    public string ExternalId { get; set; }

    public int ClaimRequesterTypeId { get; set; }

    public int ClaimModuleId { get; set; }

    public int ClaimStatusId { get; set; }

    public string ClaimStatusName { get; set; }

    public string PolicyNo { get; set; }

    public string AccidentReportNumber { get; set; }

    public string NationalId { get; set; }

    public string MobileNo { get; set; }

    public string Iban { get; set; }

    public int? InsuredBankCode { get; set; }

    public int? LicenseTypeCode { get; set; }

    public string LicenseExpiryDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}