// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserNotifications
{
    public int Id { get; set; }

    public string MessageId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreationDate { get; set; }

    public string UserId { get; set; }

    public string ReferenceId { get; set; }
}