// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserClaimFile
{
    public int Id { get; set; }

    public int ClaimHistoryId { get; set; }

    public string ClaimFilePath { get; set; }

    public string ClaimFileName { get; set; }

    public string ClaimFileExtension { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}