// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserPurchasedPromotionPrograms
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public int PromotionProgramId { get; set; }

    public int? InsuranceCompanyId { get; set; }

    public virtual InsuranceCompany InsuranceCompany { get; set; }

    public virtual PromotionProgram PromotionProgram { get; set; }

    public virtual AspNetUsers User { get; set; }
}