// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserClaimHistory
{
    public int Id { get; set; }

    public int ClaimId { get; set; }

    public int ClaimStatusId { get; set; }

    public string ClaimStatusName { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}