// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserTicketHistory
{
    public int Id { get; set; }

    public int? TicketId { get; set; }

    public int? TicketStatusId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string AdminReply { get; set; }

    public string RepliedBy { get; set; }
}