// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserTicketStatus
{
    public int Id { get; set; }

    public string StatusNameAr { get; set; }

    public string StatusNameEn { get; set; }
}