// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class UserTicketAttachment
{
    public int Id { get; set; }

    public string AttachmentPath { get; set; }

    public int? TicketId { get; set; }
}