// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class VehicleColor
{
    public byte Code { get; set; }

    public string EnglishDescription { get; set; }

    public string ArabicDescription { get; set; }

    public long? YakeenCode { get; set; }

    public string YakeenColor { get; set; }

    public long? TawuniyaCode { get; set; }

    public long? WataniyaCode { get; set; }

    public long? WataniyaAutoleaseCode { get; set; }
}