// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class VehicleMaker
{
    public short Code { get; set; }

    public string EnglishDescription { get; set; }

    public string ArabicDescription { get; set; }

    public short? TawuniyaCode { get; set; }

    public short? WataniyaCode { get; set; }

    public virtual ICollection<VehicleModel> VehicleModel { get; set; } = new List<VehicleModel>();
}