// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class VehicleDiscounts
{
    public int Id { get; set; }

    public string Nin { get; set; }

    public Guid? VehicleId { get; set; }

    public string DiscountCode { get; set; }

    public bool? IsUsed { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string PreviousReferenceId { get; set; }

    public string ReferenceId { get; set; }

    public string SequenceNumber { get; set; }

    public string CustomCardNumber { get; set; }
}