// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.DomainEntities.Entities.DomainEntities;

public partial class WareefDescounts
{
    public int Id { get; set; }

    public string DescountValue { get; set; }

    public bool? IsDeleted { get; set; }

    public int? WareefId { get; set; }

    public string WdescountCode { get; set; }
}