// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inquiry.API.Persistence.AutoLeaseLogModels.Persistence.AutoLeaseLogModels
{
    public partial class GetInsuranceCompanyAvgResponseTimeResult
    {
        public string CompanyName { get; set; }
        public int? CompanyId { get; set; }
        public double? AvgTotalResponseTimeInSeconds { get; set; }
    }
}
