// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inquiry.API.Persistence.AutoLeaseLogModels.Persistence.AutoLeaseLogModels
{
    public partial class GetPolicyNotificationsLogResult
    {
        public string companyName { get; set; }
        public string policyNo { get; set; }
        public string referenceId { get; set; }
        public string statusDescription { get; set; }
        public string ServiceRequest { get; set; }
    }
}
