// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inquiry.API.Persistence.AutoLeaseLogModels.Persistence.AutoLeaseLogModels
{
    public partial class GetQuotationStatusResult
    {
        public int? TotalCount { get; set; }
        public string CompanyName { get; set; }
        public int? ErrorCode { get; set; }
    }
}
