// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inquiry.API.Persistence.AutoLeaseLogModels.Persistence.AutoLeaseLogModels
{
    public partial class TabbyWebHookServiceRequestLogResult
    {
        public int Id { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Method { get; set; }
        public int? CompanyID { get; set; }
        public string CompanyName { get; set; }
        public int? ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string ServiceRequest { get; set; }
        public string ServiceResponse { get; set; }
        public double? ServiceResponseTimeInSeconds { get; set; }
        public string ReferenceId { get; set; }
        public string DriverNin { get; set; }
        public string VehicleId { get; set; }
        public string ServerIP { get; set; }
        public string Channel { get; set; }
    }
}
