// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.Entities.LogEntities;

public partial class IvrservicesLogs
{
    public int Id { get; set; }

    public string ServiceRequest { get; set; }

    public int ModuleId { get; set; }

    public string ModuleName { get; set; }

    public int? ErrorCode { get; set; }

    public string ErrorDescription { get; set; }

    public string Method { get; set; }

    public DateTime CreatedDate { get; set; }

    public decimal? ServiceResponseTimeInSeconds { get; set; }

    public string ServerIp { get; set; }

    public string UserIp { get; set; }

    public string UserAgent { get; set; }

    public string RequesterUrl { get; set; }
}