// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Common.Domain.Entities.LogEntities;

public partial class NotPurchasedQuotations
{
    public string ReferenceId { get; set; }

    public int InsuranceCompanyId { get; set; }

    public DateTime? CreateDateTime { get; set; }
}